# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('control_area', models.CharField(max_length=200)),
                ('created_by_human', models.BooleanField()),
                ('csv_row', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('interval', models.IntegerField(default=0)),
                ('line_name', models.CharField(max_length=200)),
                ('odometer_entries', models.BigIntegerField(default=0)),
                ('odometer_exits', models.BigIntegerField(default=0)),
                ('remote_unit', models.CharField(max_length=200)),
                ('scp', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=200)),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
    ]
