# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
