# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20160226_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='control_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='csv_row',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='cummulative_flow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='division',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='interval',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='line_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='net_flow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='net_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='odometer_entries',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='odometer_exits',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='remote_unit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='scp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='station',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
