# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20160226_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='entries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='exits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
