# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20160226_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
